name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy será acionado ao push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checar o código do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Certifique-se de usar a mesma versão do Angular

      # 3. Instalar dependências
      - name: Install Dependencies
        run: npm install

      # 4. Build da aplicação
      - name: Build Application
        run: npm run build -- --base-href /mangadex-person/

      # 5. Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Branch onde os arquivos serão publicados
          folder: dist/mangadex-person/browser  # Substitua <nome-do-projeto> pelo nome da pasta gerada no build
